### ISSUE TITLE
error on android 

### ISSUE THREAD

**Issue by kldMohammed** [HttpRequester/Requester#1]
when i try it i got this error

03-01 07:46:40.025 2809-2841/co.afterone.webservicesdemo E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                                           Process: co.afterone.webservicesdemo, PID: 2809
                                                                           java.lang.NullPointerException
                                                                               at ir.bpadashi.requester.RequesterRunnable.run(RequesterRunnable.java:239)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                               at java.lang.Thread.run(Thread.java:841)

**Comment by babakpadashi** [comment]
you didnt set RequestMethod . set It to POST or GET or SOAP
ex:
.setRequestMethod(RequestMethod.GET)

**Comment by babakpadashi** [comment]
closed
